[package]
name = "bevy-async-task"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
futures = "0.3"
# WASM compatible features only!
tokio = { version = "1", default-features = false, features = [
  "sync",
  "macros",
  "io-util",
  "rt",
  "time",
] }
bevy = { git = "https://github.com/bevyengine/bevy.git", rev = "3d752105644a18fb1dd1220d6f15e0a7eb49f04a", default-features = false }

[dev-dependencies]
async-std = "1.12"
futures-timer = "3.0"

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-futures = "0.4"
wasm-bindgen-test = "0.3"
