[package]
name = "bevy-async-task"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
futures = "0.3"
bevy = { version = "0.11", default-features = false }

[dev-dependencies]
async-std = "1.12"
futures-timer = "3.0"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio = { version = "1", features = ["full"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-futures = "0.4"
wasm-bindgen-test = "0.3"
