[package]
name = "bevy-async-task"
description = "Ergonomic abstractions to async programming in Bevy"
license = "MIT or Apache 2.0"
authors = ["Spencer C. Imbleau"]
keywords = ["gamedev", "async"]
version = "1.0.0"
edition = "2021"

[lib]

[dependencies]
futures = "0.3"
bevy = { version = "0.11", default-features = false }
cfg-if = "1.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
async-compat = "0.2"

[dev-dependencies]
async-std = "1.12"
futures-timer = "3.0"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
tokio = { version = "1", features = ["full"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-futures = "0.4"
wasm-bindgen-test = "0.3"
